name: Tests
on:
  push:
    branches:
      - master
      - "*-stable"
      - "*/ci-check"
  pull_request:

jobs:
  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, 3.0]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake
